//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
public class GoblinSteering : BasicSteering
{
    public ContactPoint2D SurfaceContact { get; set; }
    public List<GameObject> Targets { get; set; }
	protected override void Start()
	{
        Targets = new List<GameObject>();
        SetStrategy(new GoblinFloatStartegy(this));
	}
    protected void OnCollisionEnter2D(Collision2D collider)
    {
        if(collider.collider.name=="New Terrain2D")
        {
            SetStrategy(new GoblinMoveStrategy(this));
        }
        else if (collider.contacts[0].point[0]>transform.position[0])
        {
            SetStrategy(new GoblnCombatStrategy(this));
            if (!Targets.Contains(collider.collider.gameObject))
                Targets.Add(collider.collider.gameObject);
        }
    }
    protected void OnCollisionExit2D(Collision2D collider)
    {
        if (collider.collider.name == "New Terrain2D")
        {
            SetStrategy(new GoblinFloatStartegy(this));
        }
        else
        {
            RemoveTarget(collider.collider.gameObject);
            
        }
    }
    public void RemoveTarget(GameObject target)
    {
        Targets.Remove(target);
        if(Targets.Count==0)
        {
            SetStrategy(new GoblinMoveStrategy(this));
        }
    }
    protected void OnCollisionStay2D(Collision2D contact)
    {
        if(contact.gameObject.name=="New Terrain2D")
            SurfaceContact = contact.contacts[contact.contacts.Length-1];
    }
}

