//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public abstract class CreatableObject : PhysicsObject
{
	public virtual string iconName
	{
		get;
		private set;
	}

	public virtual int Price
	{
		get;
		private set;
	}

	public virtual void SetAngleOnCreation(Single angle)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RotateOnCreation(Single angle)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ScaleOnCreation(Single scale)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetScaleOnCreation(Single scale)
	{
		throw new System.NotImplementedException();
	}

	public virtual void DragOnCretaion(Vector2 position)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Place()
	{
		throw new System.NotImplementedException();
	}

	public CreatableObject()
	{
	}

}

