//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using UnityEngine.UI;

public class CreateObjectButton : MonoBehaviour
{
	private static int s_buttonCount;

	private Button m_parentButton;

	private Color m_normalColor;

	private Color m_highLitedColor;

	private Color m_pressedColor;

	public Image m_prefabImage;

	public CreatableObject m_prefab;

	private void Start()
	{
		throw new System.NotImplementedException();
	}

	public virtual void InitButton(int position)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetPressed()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Release()
	{
		throw new System.NotImplementedException();
	}

	public CreateObjectButton()
	{
	}

}

