//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class Spawner : MonoBehaviour
{
	public List<MobWave> MobWaves;

	private Single m_timeLeft;

	private void Spawn(GameObject mob)
	{
		throw new System.NotImplementedException();
	}

	private void Update()
	{
		throw new System.NotImplementedException();
	}

	private void Reset()
	{
		throw new System.NotImplementedException();
	}

	public Spawner()
	{
	}

}

