//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class BasicSteering : MonoBehaviour
{
	private BasicSteeringStrategy Strategy
	{
		private get;
		private set;
	}

	protected virtual void Start()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetStrategy(BasicSteeringStrategy strategy)
	{
		throw new System.NotImplementedException();
	}

	protected virtual void FixedUpdate()
	{
		throw new System.NotImplementedException();
	}

	public BasicSteering()
	{
	}

}

