//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class PhysicsObject : MonoBehaviour
{
	public Single Mass;

	public Single Strength;

	private Single m_energy;

	protected virtual void Start()
	{
		throw new System.NotImplementedException();
	}

	protected virtual void OnCollisionEnter2D(Collision2D collision)
	{
		throw new System.NotImplementedException();
	}

	protected virtual void OnCollisionExit2D(Collision2D collision)
	{
		throw new System.NotImplementedException();
	}

	protected virtual void OnHit(HitInfo info)
	{
		throw new System.NotImplementedException();
	}

	protected virtual void FixedUpdate()
	{
		throw new System.NotImplementedException();
	}

	public PhysicsObject()
	{
	}

}

