//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class Terrain : PhysicsObject
{
	private static List<Terrain> s_terrainComponents;

	protected override void OnCollisionEnter2D(Collision2D collision)
	{
		throw new System.NotImplementedException();
	}

	protected override void OnCollisionExit2D(Collision2D collision)
	{
		throw new System.NotImplementedException();
	}

	protected override void OnHit(HitInfo info)
	{
		throw new System.NotImplementedException();
	}

	protected override void FixedUpdate()
	{
		throw new System.NotImplementedException();
	}

	public static Vector2 GetTerrainNormal(Single x)
	{
		throw new System.NotImplementedException();
	}

	private int GetPointPosition(Single x)
	{
		throw new System.NotImplementedException();
	}

	protected override void Start()
	{
		throw new System.NotImplementedException();
	}

	public Terrain()
	{
	}

}

