//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using UnityEngine.UI;

public class Level : MonoBehaviour
{
	public static Level CurrentLevel
	{
		get;
		private set;
	}

	private static Level m_levelObject;

	public GameObject MainTower;

	public int ResourceAmount;

	public Text ResourceAmountDisplay;

	private int m_mobNumber;

	private void Start()
	{
		throw new System.NotImplementedException();
	}

	private void Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual void MobSpawned()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateObject(CreatableObject obj)
	{
		throw new System.NotImplementedException();
	}

	public virtual void OnObjectDestroyed(PhysicsObject obj)
	{
		throw new System.NotImplementedException();
	}

	public virtual void MobDestroyed()
	{
		throw new System.NotImplementedException();
	}

	public virtual void WavesFinished()
	{
		throw new System.NotImplementedException();
	}

	public virtual void FinishLevel(bool isVictory)
	{
		throw new System.NotImplementedException();
	}

	public Level()
	{
	}

}

