//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public abstract class PhysicsObject : MonoBehaviour
{
    public float Mass;
    public float Strength;
    
    
	protected abstract  void Start();

	protected abstract void FixedUpdate();
	
    protected abstract void OnCollisionEnter2D(Collision2D collision);
     
    protected abstract void OnCollisionExit2D(Collision2D collision);

    protected virtual void OnHit(HitInfo info)
    {

    }
    
}
public struct HitInfo
{
    public Vector2 velocity;
    public float mass;
    public float hitEnergy;

}

