//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
[RequireComponent(typeof(EdgeCollider2D))]
public class Terrain : PhysicsObject
{
    
    static List<Terrain> s_terrainComponents= new List<Terrain>();
    public static ScreenBounds GetScreenBounds()
    {
        const float bound = 0.1f;
        s_terrainComponents.ForEach(x => Debug.Log(x.transform.position));
        ScreenBounds bounds = new ScreenBounds();
        Terrain element = s_terrainComponents[0];
        bounds.left = element.transform.position.x+bound;
        bounds.bottom = element.transform.position.y+bound;
        bounds.top = element.transform.position.x+element.GetComponent<TerrainEditor2D>().Height-bound;
        element = s_terrainComponents[s_terrainComponents.Count - 1];
        bounds.right = element.transform.position.x + element.GetComponent<TerrainEditor2D>().Width-bound;
        return bounds;
    }
    protected override void Start()
    {
        if (!s_terrainComponents.Contains(this))
            s_terrainComponents.Add(this);
        s_terrainComponents=s_terrainComponents.OrderBy(x => x.transform.position.x).ToList();
    }
	protected override void OnCollisionEnter2D(Collision2D collision)
	{
	}

	protected override void OnCollisionExit2D(Collision2D collision)
	{
	}

	protected override void OnHit(HitInfo info)
	{
	}

	protected override void FixedUpdate()
	{
	}
}

