//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
public class JumpingGoblinLocomotion : GoblinLocomotion
{
    public Animator m_animator;
    int m_parachuteOpenTrigger = Animator.StringToHash("ParachuteOpenTrigger");
    int m_parachuteCloseTrigger = Animator.StringToHash("ParachuteCloseTrigger");
    bool m_parachuteOpen = false;
	public virtual void Jump(Vector2 direction)
	{
        GetComponent<Rigidbody2D>().velocity += direction;
        GetComponent<JumpingGoblinPhysics>().SetJump();

	}
    public virtual void Break(float k)
    {
      GetComponent<Rigidbody2D>().AddForce(-GetComponent<Rigidbody2D>().velocity*k);
    }

    public void ParachuteOpen()
    {
        if (m_parachuteOpen) return;
        m_animator.SetTrigger(m_parachuteOpenTrigger);
        m_parachuteOpen = true;

    }

    public void ParachuteClose()
    {
        if (!m_parachuteOpen) return;
        m_animator.SetTrigger(m_parachuteCloseTrigger);
        m_parachuteOpen = false;
    }
}

