//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class JumpingGoblinFloatStrategy : GoblinFloatStartegy
{
	public override void Steer(BasicSteering controller)
	{
        if (controller.GetComponent<Rigidbody2D>().velocity.y < -1.5)
        {
            controller.SendMessage("Break", 4f);
            controller.SendMessage("ParachuteOpen");
            float angle = controller.transform.rotation.eulerAngles.z;
            if (angle > 180)
                angle -= 360;
            controller.GetComponent<Rigidbody2D>().AddTorque(-angle * 0.01f);
        }

	}
    public override void ExitState(BasicSteering controller)
    {
        controller.SendMessage("ParachuteClose");
    }
}

