//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
public class JumpingGoblinMoveStrategy : GoblinMoveStrategy
{
    public static new JumpingGoblinMoveStrategy Instance()
    {
        if (s_strategy == null)
                s_strategy = new JumpingGoblinMoveStrategy();
        return s_strategy;
    }
    static JumpingGoblinMoveStrategy s_strategy;
    protected JumpingGoblinMoveStrategy()
    {
    }

    public override void SteerOther(BasicSteering controller)
    {
        GoblinSteering steering = controller as GoblinSteering;
        if (steering.SurfaceContact.normal == Vector2.zero)
        {
            controller.SetStrategy(JumpingGoblinFloatStrategy.Instance());
        }

        GoblinCombatStrategy.CheckTargets(steering,2);
        if (steering.Targets.Count != 0)
        {
            controller.SetStrategy(JumpingGoblinCombatStrategy.Instance());
        }

    }
}

