//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
public class GoblinMoveStrategy : BasicSteeringStrategy
{
    public GoblinMoveStrategy()
    {
        
    }
    public virtual void Steer(BasicSteering parent)
    {
        GoblinSteering parentController = parent as GoblinSteering;
        Vector2 normal = parentController.SurfaceContact.normal;
        if (normal == Vector2.zero)
            normal = Vector2.up;
        float angle = 0;
        angle = Vector2.Angle(parentController.transform.up, normal) * Mathf.Sign(parentController.transform.up.x - normal.x);
        angle = Utility.NormalizeAngle(angle);
        parentController.SendMessage("MoveForward", 20);
        parentController.SendMessage("KeepBalance", angle);
        
    }



    public virtual void ExitState(BasicSteering controller)
    {
        
    }

    public virtual void EnterState(BasicSteering controller)
    {
        
    }
}

