//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
public class GoblinFloatStrategy : BasicSteeringStrategy
{
    public static GoblinFloatStrategy Instance()
    {
        if (s_strategy == null)
            s_strategy = new GoblinFloatStrategy();
        return s_strategy;
    }
    static GoblinFloatStrategy s_strategy;
    protected GoblinFloatStrategy()
    {

    }
	public virtual void SteerPhysics(BasicSteering controller)
	{
     
        
	}
    public virtual void SteerOther(BasicSteering controller)
    {
        GoblinSteering steering = controller as GoblinSteering;
        if (steering.SurfaceContact.normal != Vector2.zero)
        {
            controller.SetStrategy(GoblinMoveStrategy.Instance());
        }
    }


    public virtual void ExitState(BasicSteering controller)
    {
       
    }

    public virtual void EnterState(BasicSteering controller)
    {
        
    }


    
}

