//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
public class GoblinFloatStartegy : BasicSteeringStrategy
{

    public GoblinFloatStartegy()
    {

    }
	public void Steer(BasicSteering controller)
	{
        GoblinSteering parentController = controller as GoblinSteering;
        if (parentController.rigidbody2D.velocity.magnitude < 0.001f)
        {
            parentController.SendMessage("StandUp", parentController.SurfaceContact.normal);
        }
	}

}

