//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class GoblinLocomotion : BasicLocomotion
{
    public float m_kickCooldown = 1;
    public float m_kickEnergy = 20;
    float m_kickTime;

 
    protected override void Start()
    {
        base.Start();
        HitRange = m_defaulHitRange;
        MaxSpeed = m_defaultMaxSpeed;
    }
    public override void MoveForward(float speed)
	{
        if (GetComponent<Rigidbody2D>().velocity.magnitude < MaxSpeed|| Vector2.Dot(GetComponent<Rigidbody2D>().velocity, transform.right)<0)
           GetComponent<Rigidbody2D>().AddRelativeForce(new Vector2(speed, 0));
        
	}
    public void KeepBalance(float angle)
    {
        GetComponent<Rigidbody2D>().angularVelocity = angle;
        
        
    }
    public void StandUp(Vector2 normal)
    {

        float angle = Vector2.Angle(normal, Vector2.up);
        transform.eulerAngles=new Vector3(0,0,angle);
        //Debug.Log(transform.rotation.eulerAngles);
    }
    public override void Kick(PhysicsObject target)
    {
        if(m_kickTime>0)return;
        if (GetComponent<Collider2D>().bounds.max.x - target.GetExtents().min.x > HitRange)
        {
            MoveForward(40*Time.deltaTime/Time.fixedTime);
        }
        else
        {
            HitInfo info = new HitInfo();
            info.hitEnergy = m_kickEnergy;
            target.OnHit(info);
            GetComponent<Rigidbody2D>().velocity = -transform.right.normalized;
            
        }
        m_kickTime = m_kickCooldown;
    }
    protected override void Update()
    {
        if (m_kickTime > 0)
            m_kickTime -= Time.deltaTime;
    }
}

