//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
public class JumpingGoblinMoveStrategy : GoblinMoveStrategy
{
	public override void Steer(BasicSteering parent)
	{
		throw new System.NotImplementedException();
	}

}

