//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class JumpingGoblinSteering : GoblinSteering
{
	public virtual List<GameObject> Targets
	{
		get;
		set;
	}

	protected override void Start()
	{
		throw new System.NotImplementedException();
	}

	protected override void OnCollisionEnter2D(Collision2D collision)
	{
		throw new System.NotImplementedException();
	}

	protected override void OnCollisionExit2D(Collision2D collider)
	{
		throw new System.NotImplementedException();
	}

	protected override void OnCollisionStay2D(Collision2D collision)
	{
		throw new System.NotImplementedException();
	}

	public JumpingGoblinSteering()
	{
	}

}

