//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class JumpingGoblinSteering : GoblinSteering
{
    public float DelayTime { get; set; }
   
    //HashSet<GameObject> m_terrain = new HashSet<GameObject>();
    protected override void Start()
    {
        base.Start();
        SetStrategy(JumpingGoblinFloatStrategy.Instance());
    }
    
   
    
}

