//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;

public class JumpingGoblinFloatStrategy : GoblinFloatStartegy
{
	public override void Steer(BasicSteering controller)
	{
        Vector2 origin = new Vector2();
        origin.x = controller.collider2D.bounds.max.x;
        origin.y = controller.collider2D.bounds.min.y;
        if (controller.rigidbody2D.velocity.y<0)
        {
            controller.SendMessage("Break",1.6f);
         
        }
	}

}

