//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
public class GoblinMoveStrategy : BasicSteeringStrategy
{
    GoblinSteering m_parentController;
    public GoblinMoveStrategy(GoblinSteering parent)
    {
        m_parentController = parent;
    }
	public void Steer()
    {
        Vector2 normal = m_parentController.SurfaceContact.normal;
        float angle = 0;
        angle = Vector2.Angle(m_parentController.transform.up, normal) * Mathf.Sign(m_parentController.transform.up.x - normal.x);
        angle = Utility.NormalizeAngle(angle);
        Debug.DrawRay(m_parentController.SurfaceContact.point, m_parentController.SurfaceContact.normal, Color.red);
        Debug.DrawRay(m_parentController.SurfaceContact.point, m_parentController.transform.up);
        m_parentController.SendMessage("MoveForward", 20);
        m_parentController.SendMessage("KeepBalance", angle);
        if(m_parentController.rigidbody2D.velocity.magnitude<0.001f)
        {
            m_parentController.SendMessage("StandUp", m_parentController.SurfaceContact.normal);
        }
    }

}

